// labs/Angular/lab3/src/app/students/students.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-students',
  templateUrl: './students.component.html',
  styleUrls: ['./students.component.css']
})
export class StudentsComponent {

  @Input() DataFromregister:any;

  constructor(){
    console.log("My Table : "+this.DataFromregister);
  }
}

<div class="container-fluid">
  <div class="row">
    <table class="col-6 offset-3 w-50 mt-5 table table-striped text-center">
      <thead>
          <tr>
              <th>#</th>
              <th>Name</th>
              <th>Age</th>
          </tr>
      </thead>
      <tbody>
            <tr *ngFor="let user of DataFromregister; index as i">
                <td>{{i+1}}</td>
                <td>{{user.name}}</td>
                <td>{{user.age}}</td>
            </tr>
      </tbody>
    </table>
  </div>
</div>

// labs/Reactjs/lab2/src/components/students/Students.js
const Students = ({students}) =>{


let  RenderStudents = (students)=>{
    console.log("from register"+students);
        
    if(students)
        {
         return(
            students.map((student, index)=>(
                <tr key={index}>
                    <td>{student.name}</td>
                    <td>{student.age}</td>
                </tr>
                ))
         )   
        }
    }
    return(
        <div className="container-fluid">
            <h1 className="text-center">Students</h1>
            <div className="row">
                <table className="col-6 offset-3 w-50  table table-striped text-center table-bordered">
                <thead>
                    <tr>

                        <th>Name</th>
                        <th>Age</th>
                    </tr>
                </thead>
                    <tbody>
                        { RenderStudents(students) }
                    </tbody>
                </table>
            </div>
        </div>
    )
}

export default Students;
