// labs/Reactjs/lab2/src/components/students/Students.js
const Students = ({students}) =>{


let  RenderStudents = (students)=>{
    console.log("from register"+students);
        
    if(students)
        {
         return(
            students.map((student, index)=>(
                <tr key={index}>
                    <td>{student.name}</td>
                    <td>{student.age}</td>
                </tr>
                ))
         )   
        }
    }
    return(
        <div className="container-fluid">
            <h1 className="text-center">Students</h1>
            <div className="row">
                <table className="col-6 offset-3 w-50  table table-striped text-center table-bordered">
                <thead>
                    <tr>

                        <th>Name</th>
                        <th>Age</th>
                    </tr>
                </thead>
                    <tbody>
                        { RenderStudents(students) }
                    </tbody>
                </table>
            </div>
        </div>
    )
}

export default Students;

// labs/Angular/lab4/src/app/students/students.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-students',
  templateUrl: './students.component.html',
  styleUrls: ['./students.component.css']
})
export class StudentsComponent {
   DataFromregister:any = [
    {name:"shehab", age: 25},
    {name:"ahmed", age: 22},
    {name:"mostafa", age: 23},
    {name:"ziad", age: 20},
    {name:"hossam", age: 35},
    {name:"mariam", age: 22},
    {name:"basma", age: 22},
    {name:"malak", age: 33},
    {name:"akram", age: 26},
    {name:"ayman", age: 23},
   ];

}

<div class="container-fluid">
  <div class="row">
    <table class="col-6 offset-3 w-50 mt-5 table table-striped text-center table-bordered">
      <thead>
          <tr>
              <th>#</th>
              <th>Name</th>
              <th>Age</th>
              <th>View</th>
          </tr>
      </thead>
      <tbody>
            <tr *ngFor="let user of DataFromregister; index as i">
                <td>{{i+1}}</td>
                <td>{{user.name}}</td>
                <td>{{user.age}}</td>
                <td><a href="/studentDetails/{{i}}"><i class="fa-solid fa-eye fa-lg text-dark"></i></a></td>
            </tr>
      </tbody>
    </table>
  </div>
</div>
